### ISSUE TITLE
Won't import

### ISSUE THREAD

**Issue by devergranne** [sumdog/jekyll-oldcomments#1]
I'm trying to import old comments, i never worked with Ruby before but i'm a little surprised with the error : 
```
/Library/Ruby/Gems/2.3.0/gems/jekyll-oldcomments-0.5.1/bin/wp_comments2jekyll:17:in `block in <top (required)>': undefined method `tr' for nil:NilClass (NoMethodError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rexml/xpath.rb:68:in `each'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rexml/xpath.rb:68:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/jekyll-oldcomments-0.5.1/bin/wp_comments2jekyll:15:in `<top (required)>'
	from /usr/local/bin/wp_comments2jekyll:22:in `load'
	from /usr/local/bin/wp_comments2jekyll:22:in `<main>'

```

Now, the problem seems to lie here : 

  c_map['title'] = item.elements['title'].text.tr(':','')

**Comment by sumdog** [comment]
I think this line was designed to replace all colons in titles with spaces. I think this was for formatting the YAML front matter (really I should have just quoted the text in the front matter). 

I'm guessing you probably have some posts with null titles? Try just removing the `.tr` part and get just the text. You should be able to clone it and run the script locally.

**Comment by devergranne** [comment]
Thanks for your quick reply. I changed that:

`c_map['title'] = item.elements['title'].text.tr(':','')`

to that :

`c_map['title'] = item.elements['title'].text`

And the import is working, however I do have semi columns on some titles, so when i'm trying to generate my site it's crashing : 

```
Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: (/xxx/_comments/58945-2016-08-15-xxx.md): mapping values are not allowed in this context at line 2 column 34 in /_layouts/post.html
jekyll 3.4.3 | Error:  (/xxx/_comments/58945-2016-08-15-xxx.md): mapping values are not allowed in this context at line 2 column 34

```
I don't program in Ruby but I think if we'd did something like : 

```
if  item.elements['title'].text contains ':' 
       remove the ":",
else 
       item.elements['title'].text
```

Could work
